### ISSUE TITLE
动态链接问题

### ISSUE THREAD

**Issue by Tpomelos** [zhou13/uastar#1]
您好，我在linux cmake 出工程后，再make编译的时候出现了：
collect2: error ld returned 1 exit status
make [2]:***[demo-sort]错误1
make[1]: *** [CMakeFiles/demo-sort.dir/all] 错误 2
make: *** [all] 错误 2
的动态链接错误，不知道您是否遇到过？

**Comment by zhou13** [comment]
@Tpomelos 你给的错误信息不完整。

**Comment by Tpomelos** [comment]
CMakeFiles/demo-sort.dir/libs/moderngpu/src/demo-sort_generated_mgpucontext.cu.o：在函数‘__gnu_cxx::new_allocator<std::pair<int const, std::_List_iterator<mgpu::CudaAllocBuckets::MemNode> > >::construct(std::pair<int const, std::_List_iterator<mgpu::CudaAllocBuckets::MemNode> >*, std::pair<int const, std::_List_iterator<mgpu::CudaAllocBuckets::MemNode> > const&)’中：
/usr/include/c++/4.8/ext/new_allocator.h:130：对‘__asan_report_store16’未定义的引用
/usr/include/c++/4.8/ext/new_allocator.h:130：对‘__asan_report_load16’未定义的引用
CMakeFiles/demo-sort.dir/libs/moderngpu/src/demo-sort_generated_mgpucontext.cu.o：在函数‘__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<void* const, std::_List_iterator<mgpu::CudaAllocBuckets::MemNode> > > >::allocate(unsigned long, void const*)’中：
/usr/include/c++/4.8/ext/new_allocator.h:102：对‘__asan_handle_no_return’未定义的引用
CMakeFiles/demo-sort.dir/libs/moderngpu/src/demo-sort_generated_mgpucontext.cu.o：在函数‘__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, std::_List_iterator<mgpu::CudaAllocBuckets::MemNode> > > >::allocate(unsigned long, void const*)’中：
/usr/include/c++/4.8/ext/new_allocator.h:102：对‘__asan_handle_no_return’未定义的引用
CMakeFiles/demo-sort.dir/libs/moderngpu/src/demo-sort_generated_mgpucontext.cu.o：在函数‘std::auto_ptr<mgpu::DeviceGroup>::~auto_ptr()’中：
/usr/include/c++/4.8/backward/auto_ptr.h:170：对‘__asan_report_load8’未定义的引用
CMakeFiles/demo-sort.dir/libs/moderngpu/src/demo-sort_generated_mgpucontext.cu.o：在函数‘std::auto_ptr<mgpu::ContextGroup>::~auto_ptr()’中：
/usr/include/c++/4.8/backward/auto_ptr.h:170：对‘__asan_report_load8’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [demo-sort] 错误 1
make[1]: *** [CMakeFiles/demo-sort.dir/all] 错误 2
make: *** [all] 错误 2
前面等 一些类似的错误，不知道您是否遇到过？

**Comment by zhou13** [comment]
看起来你的gcc的memory sanitizer library有些问题，debug模式会启动-fsanitize=address。

你可以试试删除你的build文件夹然后用以下命令生成Makefile
````
cmake -DCMAKE_BUILD_TYPE=Release ..
````

**Comment by Tpomelos** [comment]
谢谢您的耐心解答，这个问题已经解决了。之后运行的时候，可能是设备的问题会提示NOT COMPILED WITH COMPATIBLE PTX VERSION FOR DEVICE 0
cudaMalloc error 2

最后还是要谢谢您。

**Comment by zhou13** [comment]
这应该是你GPU支持的CUDA版本老旧，你可以修改CMakeList.txt里有关GPU架构的参数：`arch=compute_35,code=sm_35`，我估计你需要调低，不过我没有测试过在低版本上的效果。

**Comment by Tpomelos** [comment]
按照您的建议改好了，谢谢您！

**Comment by Tpomelos** [comment]
再打扰一下，如果想单步追踪一下您的程序的话，需要怎么操作哇。

**Comment by zhou13** [comment]
与此项目无关的问题不应该在这里讨论。你可以上stackoverflow发帖求助。

我的话好久没单步调试过了。

**Comment by Tpomelos** [comment]
谢谢 您
